spring.application.name=agenda-api

spring.datasource.url=jdbc:postgresql://localhost:5432/agenda_db
spring.datasource.username=agenda_user
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false